project:
  type: website
  # Render the mini-site into the main site’s folder so links work
  output-dir: C:/dreytwy/TH3/_site/   # ← NEW
  
website:
  title: "Covert Reef <img src='img/coral.png' style='height:1.2em; vertical-align:middle;'>"
  
  # ▸ turn OFF Quarto’s default top navbar & footer
  navbar: false        # ← NEW

  sidebar:
    style: "docked"
    search: true
    collapse-level: 0
    contents:
      - href: Take-home_Ex03.qmd
        text: Home
      - href: Introduction.qmd
        text: Introduction        
      - href: Storyboard_UI_Design.qmd
        text: Storyboard UI Design
      - href: r_packg.qmd
        text: Required R Packages   
      - href: Prototype.qmd
        text: Prototype in Netlify
      - href: shiny_under_construction.qmd
        text: Prototype translated to Shiny
      - href: https://isss608-ay2024-25-dreytwy.netlify.app/
        text: Back to Root Netlify
        
format:
  html:
    theme: journal
    toc: true
    toc-depth: 2
    code-fold: true
    code-summary: "Show the code"
    css: ex03-style.css   

editor: visual
